# Using DandelionPolars

In [ ]:
import os
import scanpy as sc
import polars as pl

from dandelion.utilities._polars import DandelionPolars, load_polars

os.chdir(
    "/Users/uqztuong/Documents/GitHub/dandelion/docs/notebooks/dandelion_tutorial"
)
df = load_polars("human-bcr-1m/bcr_annotation_airr_fixed.tsv")
sc.settings.verbosity = 3  # set scanpy verbosity to show info messages

In [2]:
vdj = DandelionPolars(df)
vdj

Lazy Dandelion object with n_obs = 1208221 and n_contigs = 3919765
    data: sequence_id, sequence, locus, rev_comp, productive, v_call, d_call, j_call, c_call, sequence_alignment, germline_alignment, cdr1, cdr2, junction, junction_aa, v_cigar, d_cigar, j_cigar, v_identity, j_identity, cell_id, complete_vdj, full_length, consensus_count, umi_count, rearrangement_status
    metadata: cell_id, locus_VDJ, locus_VJ, productive_VDJ, productive_VJ, v_call_VDJ, v_call_VJ, d_call_VDJ, j_call_VDJ, j_call_VJ, c_call_VDJ, c_call_VJ, junction_VDJ, junction_VJ, junction_aa_VDJ, junction_aa_VJ, umi_count_VDJ, umi_count_VJ, locus_VDJ_main, locus_VJ_main, productive_VDJ_main, productive_VJ_main, v_call_VDJ_main, v_call_VJ_main, d_call_VDJ_main, j_call_VDJ_main, j_call_VJ_main, c_call_VDJ_main, c_call_VJ_main, junction_VDJ_main, junction_VJ_main, junction_aa_VDJ_main, junction_aa_VJ_main, umi_count_VDJ_main, umi_count_VJ_main, isotype, isotype_main, isotype_status, locus_status, chain_status, rearrangement_status_VDJ, rearrangement_status_VJ

In [ ]:
# Filter by a specific sequence_id using boolean series
vdj[vdj.data.cell_id.isin(["29_19_44__s1"])].metadata.collect()

shape: (1, 43)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ cell_id   ┆ locus_VDJ ┆ locus_VJ ┆ productiv ┆ … ┆ chain_sta ┆ rearrange ┆ rearrange ┆ test_meta │
│ ---       ┆ ---       ┆ ---      ┆ e_VDJ     ┆   ┆ tus       ┆ ment_stat ┆ ment_stat ┆ data_col  │
│ str       ┆ str       ┆ str      ┆ ---       ┆   ┆ ---       ┆ us_VDJ    ┆ us_VJ     ┆ ---       │
│           ┆           ┆          ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str       │
│           ┆           ┆          ┆           ┆   ┆           ┆ str       ┆ str       ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 29_19_44_ ┆ IGH|IGH   ┆ IGK      ┆ T|T       ┆ … ┆ Extra     ┆ Multi     ┆ Standard  ┆ test_valu │
│ _s1       ┆           ┆          ┆           ┆   ┆ pair      ┆           ┆           ┆ e         │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [12]:
vdj.metadata.collect()

shape: (1_208_221, 43)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cell_id   ┆ locus_VDJ ┆ locus_VJ  ┆ productiv ┆ … ┆ chain_sta ┆ rearrange ┆ rearrange ┆ test_met │
│ ---       ┆ ---       ┆ ---       ┆ e_VDJ     ┆   ┆ tus       ┆ ment_stat ┆ ment_stat ┆ adata_co │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ us_VDJ    ┆ us_VJ     ┆ l        │
│           ┆           ┆           ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 29_06_36_ ┆ IGH       ┆ IGK       ┆ T         ┆ … ┆ Single    ┆ Standard  ┆ Standard  ┆ test_val │
│ _s1       ┆           ┆           ┆           ┆   ┆ pair      ┆           ┆           ┆ ue       │
│ 29_19_44_ ┆ IGH|IGH   ┆ IGK       ┆ T|T       ┆ … ┆ Extra     ┆ Multi     ┆ Standard  ┆ test_val │
│ _s1       ┆           ┆           ┆           ┆   ┆ pair      ┆           ┆           ┆ ue       │
│ 29_77_30_ ┆ IGH       ┆ IGL       ┆ T         ┆ … ┆ Single    ┆ Standard  ┆ Standard  ┆ test_val │
│ _s1       ┆           ┆           ┆           ┆   ┆ pair      ┆           ┆           ┆ ue       │
│ 27_90_56_ ┆ IGH|IGH   ┆ IGL|IGL   ┆ T|T       ┆ … ┆ Extra     ┆ Multi     ┆ Multi     ┆ test_val │
│ _s1       ┆           ┆           ┆           ┆   ┆ pair      ┆           ┆           ┆ ue       │
│ 29_76_22_ ┆ IGH       ┆ IGL       ┆ T         ┆ … ┆ Single    ┆ Standard  ┆ Standard  ┆ test_val │
│ _s1       ┆           ┆           ┆           ┆   ┆ pair      ┆           ┆           ┆ ue       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 02_44_76_ ┆ IGH       ┆ IGK       ┆ T         ┆ … ┆ Single    ┆ Standard  ┆ Standard  ┆ test_val │
│ _s16      ┆           ┆           ┆           ┆   ┆ pair      ┆           ┆           ┆ ue       │
│ 01_74_25_ ┆ IGH|IGH|I ┆ IGK|IGK|I ┆ T|T|T|T   ┆ … ┆ Extra     ┆ Multi     ┆ Multi     ┆ test_val │
│ _s16      ┆ GH|IGH    ┆ GL|IGL    ┆           ┆   ┆ pair      ┆           ┆           ┆ ue       │
│ 02_45_24_ ┆ IGH       ┆ IGK|IGK   ┆ T         ┆ … ┆ Extra     ┆ Standard  ┆ Multi     ┆ test_val │
│ _s16      ┆           ┆           ┆           ┆   ┆ pair      ┆           ┆           ┆ ue       │
│ 02_07_68_ ┆ IGH       ┆ IGK       ┆ T         ┆ … ┆ Single    ┆ Standard  ┆ Standard  ┆ test_val │
│ _s16      ┆           ┆           ┆           ┆   ┆ pair      ┆           ┆           ┆ ue       │
│ 02_23_77_ ┆ IGH|IGH   ┆ IGK       ┆ T|T       ┆ … ┆ Extra     ┆ Multi     ┆ Standard  ┆ test_val │
│ _s16      ┆           ┆           ┆           ┆   ┆ pair      ┆           ┆           ┆ ue       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
vdj[
    vdj.data.filter(pl.col("sequence_id") == "29_19_44__GTCGTGTAGT__CTG1__s1")
].data.collect()

shape: (1, 26)
┌────────────┬────────────┬───────┬──────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ sequence_i ┆ sequence   ┆ locus ┆ rev_comp ┆ … ┆ full_lengt ┆ consensus_ ┆ umi_count ┆ rearrange │
│ d          ┆ ---        ┆ ---   ┆ ---      ┆   ┆ h          ┆ count      ┆ ---       ┆ ment_stat │
│ ---        ┆ str        ┆ str   ┆ str      ┆   ┆ ---        ┆ ---        ┆ f64       ┆ us        │
│ str        ┆            ┆       ┆          ┆   ┆ i64        ┆ f64        ┆           ┆ ---       │
│            ┆            ┆       ┆          ┆   ┆            ┆            ┆           ┆ str       │
╞════════════╪════════════╪═══════╪══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 29_19_44__ ┆ GTGATTATGC ┆ IGH   ┆ F        ┆ … ┆ 0          ┆ 496.0      ┆ 6.0       ┆ Standard  │
│ GTCGTGTAGT ┆ TATGAGCTGG ┆       ┆          ┆   ┆            ┆            ┆           ┆           │
│ __CTG1__s1 ┆ GTCCGCCAGG ┆       ┆          ┆   ┆            ┆            ┆           ┆           │
│            ┆ …          ┆       ┆          ┆   ┆            ┆            ┆           ┆           │
└────────────┴────────────┴───────┴──────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [5]:
vdj.data.filter(
    pl.col("sequence_id") == "29_19_44__GTCGTGTAGT__CTG1__s1"
).collect()

shape: (1, 26)
┌────────────┬────────────┬───────┬──────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ sequence_i ┆ sequence   ┆ locus ┆ rev_comp ┆ … ┆ full_lengt ┆ consensus_ ┆ umi_count ┆ rearrange │
│ d          ┆ ---        ┆ ---   ┆ ---      ┆   ┆ h          ┆ count      ┆ ---       ┆ ment_stat │
│ ---        ┆ str        ┆ str   ┆ str      ┆   ┆ ---        ┆ ---        ┆ f64       ┆ us        │
│ str        ┆            ┆       ┆          ┆   ┆ i64        ┆ f64        ┆           ┆ ---       │
│            ┆            ┆       ┆          ┆   ┆            ┆            ┆           ┆ str       │
╞════════════╪════════════╪═══════╪══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 29_19_44__ ┆ GTGATTATGC ┆ IGH   ┆ F        ┆ … ┆ 0          ┆ 496.0      ┆ 6.0       ┆ Standard  │
│ GTCGTGTAGT ┆ TATGAGCTGG ┆       ┆          ┆   ┆            ┆            ┆           ┆           │
│ __CTG1__s1 ┆ GTCCGCCAGG ┆       ┆          ┆   ┆            ┆            ┆           ┆           │
│            ┆ …          ┆       ┆          ┆   ┆            ┆            ┆           ┆           │
└────────────┴────────────┴───────┴──────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [6]:
# Force reload the module to pick up changes
import importlib
import dandelion.utilities._polars

importlib.reload(dandelion.utilities._polars)

from dandelion.utilities._polars import DandelionPolars, load_polars

# Reload everything
df = load_polars("human-bcr-1m/bcr_annotation_airr_fixed.tsv")
vdj = DandelionPolars(df)

## Test Column Assignment

Now test adding new columns to the data

In [7]:
# Test 1: Add a constant column
vdj.data["test_constant"] = 42
print("Added constant column")
print(vdj.data.select(["sequence_id", "test_constant"]).head(3).collect())

Added constant column
shape: (3, 2)
┌────────────────────────────────┬───────────────┐
│ sequence_id                    ┆ test_constant │
│ ---                            ┆ ---           │
│ str                            ┆ i64           │
╞════════════════════════════════╪═══════════════╡
│ 29_06_36__GTCAAAATAG__CTG1__s1 ┆ 42            │
│ 29_06_36__AAAAGACTCA__CTG1__s1 ┆ 42            │
│ 29_19_44__GTCGTGTAGT__CTG1__s1 ┆ 42            │
└────────────────────────────────┴───────────────┘

In [8]:
# Test 2: Add a column from an expression
vdj.data["v_gene"] = pl.col("v_call").str.extract(r"(IGH\w*)", 0)
print("Added column from expression")
print(vdj.data.select(["v_call", "v_gene"]).head(3).collect())

Added column from expression
shape: (3, 2)
┌──────────┬────────┐
│ v_call   ┆ v_gene │
│ ---      ┆ ---    │
│ str      ┆ str    │
╞══════════╪════════╡
│ IGKV1-33 ┆ null   │
│ IGHV3-15 ┆ IGHV3  │
│ IGHV3-49 ┆ IGHV3  │
└──────────┴────────┘

In [9]:
# Test 3: Add a column from arithmetic operations
vdj.data["consensus_plus_umi"] = pl.col("consensus_count") + pl.col("umi_count")
print("Added column from arithmetic operation")
print(
    vdj.data.select(["consensus_count", "umi_count", "consensus_plus_umi"])
    .head(3)
    .collect()
)

Added column from arithmetic operation
shape: (3, 3)
┌─────────────────┬───────────┬────────────────────┐
│ consensus_count ┆ umi_count ┆ consensus_plus_umi │
│ ---             ┆ ---       ┆ ---                │
│ f64             ┆ f64       ┆ f64                │
╞═════════════════╪═══════════╪════════════════════╡
│ 1825.0          ┆ 18.0      ┆ 1843.0             │
│ 283.0           ┆ 3.0       ┆ 286.0              │
│ 496.0           ┆ 6.0       ┆ 502.0              │
└─────────────────┴───────────┴────────────────────┘

In [10]:
# Test 4: Add a column to metadata
vdj.metadata["test_metadata_col"] = "test_value"
print("Added column to metadata")
print(vdj.metadata.select(["cell_id", "test_metadata_col"]).head(3).collect())

Added column to metadata
shape: (3, 2)
┌──────────────┬───────────────────┐
│ cell_id      ┆ test_metadata_col │
│ ---          ┆ ---               │
│ str          ┆ str               │
╞══════════════╪═══════════════════╡
│ 29_06_36__s1 ┆ test_value        │
│ 29_19_44__s1 ┆ test_value        │
│ 29_77_30__s1 ┆ test_value        │
└──────────────┴───────────────────┘

## Summary: Column Assignment Support

The `DataFrameAccessor` now supports pandas-like column assignment for both `.data` and `.metadata`:

### Supported Assignment Types:
1. **Constant values**: `vdj.data["col"] = 42`
2. **Lists/tuples**: `vdj.data["col"] = [1, 2, 3, ...]`
3. **Series**: `vdj.data["col"] = some_series`
4. **Expressions**: `vdj.data["col"] = pl.col("other_col") + 10`
5. **Arithmetic operations**: `vdj.data["col"] = pl.col("col1") + pl.col("col2")`

Changes made to `.data` automatically update the underlying `vdj._data`, and changes to `.metadata` update `vdj._metadata`.